import Head from 'next/head'
import Header from '../Components/Header';
import Footer from '../Components/Footer';
import Image from 'next/image';


export default function Home() {
  return (
    <>
      <Head>
        <title>Salmonella Cookies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section id="store">
          <h2>Salmonella Cookies Store</h2>
          <h3>Check out all our sweet merchandise!</h3>
          <div className='front-section'>
           
              <Image
                src="/cutter.jpeg"
                alt="Picture of a salmon cookie cutter"
                width={100}
                height={100}
              />
              <p>Salmon Cookie Cutters!</p>
           
              <Image
                src="/frosted-cookie.jpg"
                alt="Picture of a Frosted Salmon Cookie"
                width={100}
                height={100}
              />
              <p>Salmon Cookies!</p>
           
              <Image
                src="/shirt.jpg"
                alt="Picture of a Salmon T-Shirt"
                width={100}
                height={100}
              />
              <p>Salmon Shirts!</p>
          
          </div>
        </section>
        <section id='family'>
          <h2>Family Friendly!</h2>
          <Image
                src="/family.jpg"
                alt="Picture of a family"
                width={420}
                height={300}
              />
          <p className='family-pitch'>You always want the best for your family, and thats why you should buy from Salmonella Cookies. We have been a family run business since 1901. Providing Salmonella for over 100 years across the globe!</p>       
        </section>
        <section id='store-locations'>
          <h2>Locations WorldWide: Hours of Operation are 0600 to 2000 local time</h2>
          <ul>
          <li>Seattle @ 1234 Queen Anne Ave.</li>
          <li>Tokyo @ 5678 Cherry Blossom St.</li>
          <li>Dubai @ 1234 Dubai Creek Rd.</li>
          <li>Paris @ 5678 Eiffel Tower Ln.</li>
          <li>Lima @ 1234 Peru Ave. </li>
          </ul>
        </section>
      </main>
      <Footer />
    </>
  )
}
